TicketTest/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TicketTest.Models;

namespace TicketTest.Controllers
{
    public class AuthController : Controller
    {
        private DBEntities db = new DBEntities();

        public ActionResult Index()
        {
            if(!string.IsNullOrWhiteSpace(HttpContext.Request.Cookies["uid"].Value))
            {
                return Redirect("/Main/Index");
            }
            return View();
        }

        public ActionResult Authorize(string Mail, string Pass)
        {
            try
            {
                MD5 md5 = new MD5CryptoServiceProvider();
                byte[] checkSum = md5.ComputeHash(Encoding.UTF8.GetBytes(Pass));
                string result = BitConverter.ToString(checkSum).Replace("-", String.Empty);
                Pass = result;

                if (AuthCheckk(Mail, Pass))
                {
                    return Redirect("/Main/Index");
                }
            }
            catch { }
            return PartialView("FormError");
        }

        private bool AuthCheckk(string mail, string pass)
        {
            bool res = false;
            try
            {
                if (!string.IsNullOrWhiteSpace(mail) &&
                !string.IsNullOrWhiteSpace(pass))
                {
                    foreach (var v in db.User)
                    {
                        if (v.Mail.ToLower().Trim() == mail.ToLower().Trim() &&
                            v.Pass.Trim() == pass.Trim())
                        {
                            HttpContext.Response.Cookies["uid"].Value = v.ID.ToString();
                            res = true;
                        }
                    }
                }
            }
            catch { }
            return res;
        }

        public ActionResult LogOut()
        {
            HttpContext.Response.Cookies["uid"].Value = "";
            return Redirect("/Home/Index");
        }
    }
}

TicketTest/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketTest.Models;

namespace TicketTest.Controllers
{
    public class MainController : Controller
    {
        private DBEntities db = new DBEntities();

        public ActionResult Index()
        {
            return View(db.BusStation.ToList());
        }

        public ActionResult BusStationSearch(string Query)
        {
            try
            {
                if (!string.IsNullOrWhiteSpace(Query))
                {
                    List<BusStation> res = new List<BusStation>();
                    foreach (var v in db.BusStation)
                    {
                        if (v.Name.ToLower().IndexOf(Query.ToLower()) > -1)
                        {
                            res.Add(v);
                        }
                    }
                    return View(res);
                }
            }
            catch { }
            return View(db.BusStation.ToList());
        }

        public ActionResult FlightSearch(string StartPointName, string EndPointName, string Date)
        {
            try
            {
                if (!string.IsNullOrWhiteSpace(StartPointName) ||
                !string.IsNullOrWhiteSpace(EndPointName) ||
                !string.IsNullOrWhiteSpace(Date))
                {
                    int startPID = GetBusStateIDByName(StartPointName),
                        endPID = GetBusStateIDByName(EndPointName);

                    List<Flight> res = new List<Flight>();

                    foreach (var v in db.Flight)
                    {
                        int AddLim = 0;
                        if (startPID == -1)
                        {
                            AddLim++;
                        }
                        else
                        {
                            if (v.StartBusStationID == startPID)
                            {
                                AddLim++;
                            }
                        }
                        if (endPID == -1)
                        {
                            AddLim++;
                        }
                        else
                        {
                            if (v.EndBusStationID == endPID)
                            {
                                AddLim++;
                            }
                        }
                        if (string.IsNullOrWhiteSpace(Date))
                        {
                            AddLim++;
                        }
                        else
                        {
                            if (v.DateTimeFrom == Date || v.DateTimeTo == Date)
                            {
                                AddLim++;
                            }
                        }
                        if (AddLim == 3)
                        {
                            res.Add(v);
                        }
                    }

                    return View(res);
                }
            }
            catch { }
            return View(db.Flight.ToList());
        }

        private int GetBusStateIDByName(string Name)
        {
            int res = -1;
            try
            {
                foreach (var v in db.BusStation)
                {
                    if (v.Name.ToLower().IndexOf(Name.ToLower().Trim()) > -1)
                    {
                        res = v.ID;
                    }
                }
            }
            catch { }
            return res;
        }

        public ActionResult ReserveOrPurcast()
        {
            return Redirect("/Res/Index");
        }
    }
}

TicketTest/Controllers/ResController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using TicketTest.Models;

namespace TicketTest.Controllers
{
    public class ResController : Controller
    {
        private DBEntities db = new DBEntities();
        
        public ActionResult Index()
        {
            List<Order> res = new List<Order>();
            foreach(var v in db.Order)
            {
                if(v.OwnerID.ToString() == HttpContext.Request.Cookies["uid"].Value)
                {
                    res.Add(v);
                }
            }
            return View(res);
        }

        public ActionResult Reserve(string Flight)
        {
            try
            {
                if(!string.IsNullOrWhiteSpace(Flight))
                {
                    if (!string.IsNullOrWhiteSpace(HttpContext.Request.Cookies["uid"].Value))
                    {
                        int fid = -1;
                        if (!string.IsNullOrWhiteSpace(Flight))
                        {
                            fid = int.Parse(Flight);
                        }
                        Flight fl = db.Flight.Find(fid);

                        if (fl.PlacesCount > 0)
                        {
                            Order o = new Order()
                            {
                                FlightID = fid,
                                OwnerID = int.Parse(HttpContext.Request.Cookies["uid"].Value),
                                Status = "Reserved"
                            };
                            db.Order.Add(o);
                            db.SaveChanges();

                            if (fl != null)
                            {
                                fl.PlacesCount--;
                                db.SaveChanges();
                            }
                        }
                    }
                }
            }
            catch { }
            return Index();
        }

        public ActionResult Purcast(string Purcast)
        {
            try
            {
                int pc = -1;
                if (!string.IsNullOrWhiteSpace(Purcast))
                {
                    pc = int.Parse(Purcast);
                }

                Order o = db.Order.Find(pc);
                if (o != null)
                {
                    o.Status = "Purcasted";
                    db.SaveChanges();

                    Ticket t = new Ticket()
                    {
                        OrderID = o.ID,
                        Status = o.Status,
                        UserNum = o.OwnerID,
                        UserName = db.User.Find(o.OwnerID).Name.Trim(),
                        UserLname = db.User.Find(o.OwnerID).LName.Trim(),
                        UserDocNum = o.ID
                    };
                    db.Ticket.Add(t);
                    db.SaveChanges();
                }
            }
            catch { }
            return Redirect("/Res/Index");
        }

        public ActionResult Show()
        {
            return Redirect("/Res/Index");
        }
    }
}

TicketTest/Views/Res/Index.cshtml
@model  IEnumerable<TicketTest.Models.Order>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/Content/Site.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="logOut smBtn">
        @using (Html.BeginForm("LogOut", "Auth"))
        {
            <input type="submit" value="Выход" />
        }
    </div>
    @using TicketTest.Models;
    <div class="top">
        <div class="topPart">
            @using (Html.BeginForm("Reserve", "Res"))
            {
                <div class="field">
                    <select id="Flight" name="Flight">
                        @using (DBEntities db = new DBEntities())
                        {
                            foreach (var v in db.Flight)
                            {
                                <option value="@v.ID">№ @v.FlightNum Рейс: @v.FlightName</option>
                            }
                        }
                    </select>
                </div>
                <div class="smBtn">
                    <input type="submit" value="Забронировать" />
                </div>
            }
        </div>

        <div class="topPart">
            @using (Html.BeginForm("Purcast", "Res"))
            {
                <div class="field">
                    <select id="Purcast" name="Purcast">
                        @{
                            using (DBEntities db = new DBEntities())
                            {
                                foreach (var v in db.Order)
                                {
                                    if (v.OwnerID.ToString() == @HttpContext.Current.Request.Cookies["uid"].Value)
                                    {
                                        string f = db.Flight.Find(v.FlightID).FlightName;
                                        string o = db.User.Find(v.OwnerID).Name;
                                        <option value="@v.ID">
                                            Имя: @o Рейс: @f Статус: @v.Status
                                        </option>
                                    }
                                }
                            }
                        }
                    </select>
                </div>
                <div class="smBtn">
                    <input type="submit" value="Купить" />
                </div>
            }
        </div>

        <div class="topPartMain">
            <div class="longBtn">
                @using (Html.BeginForm("Index", "Main"))
                {
                    <input type="submit" value="На главную" />
                }
            </div>

            <div class="longBtn">
                @using (Html.BeginForm("Show", "Res"))
                {
                    <input type="submit" value="Показать мои заказы" />
                }
            </div>
        </div>
    </div>
    <div class="list container">
        @{
            foreach (var v in Model)
            {
                <div class="item row">
                    <div class="iSet col-md-12">
                        @{string f = "";}
                        @using (DBEntities db = new DBEntities())
                        {
                            foreach (var vv in db.Flight)
                            {
                                if (v.FlightID == vv.ID)
                                {
                                    f = vv.FlightName;
                                }
                            }
                        }
                        Название рейса: @f
                    </div>
                    <div class="iSet col-md-12">
                        Статус; @v.Status
                    </div>
                </div><br />
            }
        }
    </div>
</body>
</html>

TicketTest/Views/Res/Reserve.cshtml
@model  IEnumerable<TicketTest.Models.Order>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/Content/Site.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="logOut smBtn">
        @using (Html.BeginForm("LogOut", "Auth"))
        {
            <input type="submit" value="Выход" />
        }
    </div>
    @using TicketTest.Models;
    <div class="top">
        <div class="topPart">
            @using (Html.BeginForm("Reserve", "Res"))
            {
                <div class="field">
                    <select id="Flight" name="Flight">
                        @using (DBEntities db = new DBEntities())
                        {
                            foreach (var v in db.Flight)
                            {
                                <option value="@v.ID">№ @v.FlightNum Рейс: @v.FlightName Стоимость: @v.TicketCost</option>
                            }
                        }
                    </select>
                </div>
                <div class="smBtn">
                    <input type="submit" value="Забронировать" />
                </div>
            }
        </div>

        <div class="topPart">
            @using (Html.BeginForm("Purcast", "Res"))
            {
                <div class="field">
                    <select id="Purcast" name="Purcast">
                        @{
                            using (DBEntities db = new DBEntities())
                            {
                                foreach (var v in db.Order)
                                {
                                    if (v.OwnerID.ToString() == @HttpContext.Current.Request.Cookies["uid"].Value)
                                    {
                                        string f = db.Flight.Find(v.FlightID).FlightName;
                                        string o = db.User.Find(v.OwnerID).Name;
                                        <option value="@v.ID">
                                            Имя: @o Рейс: @f Статус: @v.Status
                                        </option>
                                    }
                                }
                            }
                        }
                    </select>
                </div>
                <div class="smBtn">
                    <input type="submit" value="Купить" />
                </div>
            }
        </div>

        <div class="topPartMain">
            <div class="longBtn">
                @using (Html.BeginForm("Index", "Main"))
                {
                    <input type="submit" value="На главную" />
                }
            </div>

            <div class="longBtn">
                @using (Html.BeginForm("Show", "Res"))
                {
                    <input type="submit" value="Показать мои заказы" />
                }
            </div>
        </div>
    </div>
    <div class="list container">
        @{
            foreach (var v in Model)
            {
                <div class="item row">
                    <div class="iSet col-md-12">
                        @{string f = "";}
                        @using (DBEntities db = new DBEntities())
                        {
                            foreach (var vv in db.Flight)
                            {
                                if (v.FlightID == vv.ID)
                                {
                                    f = vv.FlightName;
                                }
                            }
                        }
                        Название рейса: @f
                    </div>
                    <div class="iSet col-md-12">
                        Статус; @v.Status
                    </div>
                </div><br />
                            }
        }
    </div>
</body>
</html>