TicketTest/Controllers/RegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TicketTest.Models;

namespace TicketTest.Controllers
{
    public class RegController : Controller
    {
        private DBEntities db = new DBEntities();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(string Name, string LName, string Mail, string Pass, string ComformPass, string BirthDate)
        {
            try
            {
                if (!string.IsNullOrWhiteSpace(Name) &&
                !string.IsNullOrWhiteSpace(LName) &&
                !string.IsNullOrWhiteSpace(Mail) &&
                !string.IsNullOrWhiteSpace(Pass) &&
                !string.IsNullOrWhiteSpace(ComformPass) &&
                !string.IsNullOrWhiteSpace(BirthDate))
                {
                    if (!ThisUserExist(Mail) && Pass == ComformPass)
                    {
                        MD5 md5 = new MD5CryptoServiceProvider();
                        byte[] checkSum = md5.ComputeHash(Encoding.UTF8.GetBytes(Pass));
                        string result = BitConverter.ToString(checkSum).Replace("-", String.Empty);
                        Pass = result;

                        User u = new User() { Name = Name, LName = LName, Mail = Mail, Pass = Pass, BirthDate = BirthDate };
                        db.User.Add(u);
                        db.SaveChanges();

                        HttpContext.Response.Cookies["uid"].Value = "";
                        return Redirect("/Auth/Index");
                    }
                }
            }
            catch { }
            return PartialView("FormError");
        }

        public bool ThisUserExist(string Mail)
        {
            bool res = false;
            try
            {
                foreach (var v in db.User)
                {
                    if (v.Mail.ToLower().Trim() == Mail.ToLower().Trim())
                    {
                        res = true;
                        break;
                    }
                }
            }
            catch { }
            return res;
        }
    }
}

TicketTest/Views/Reg/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/Content/Site.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="top regBox">
        <div class="topPart">
            @using (Html.BeginForm("Register", "Reg", FormMethod.Post))
            {
                <div class="field register">
                    <label>Имя</label>
                    @Html.TextBox("Name");
                    <label>Фамилия</label>
                    @Html.TextBox("LName");
                    <label>Дата рождения</label>
                    <input id="BirthDate" name="BirthDate" type="date" min="1920-01-01" max="@DateTime.Today.ToString()">
                    <label>E-mail</label>
                    @Html.TextBox("Mail");
                    <label>Пароль</label>
                    @Html.Password("Pass");
                    <label>Повторите пароль</label>
                    @Html.Password("ComformPass");
                </div>
                <div class="topPartMain">
                    <div class="smBtn">
                        <input type="submit" value="Регистрация" />
                    </div>
                </div>
            }
        </div>
    </div>
</body>
</html>